/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiKeyStreamProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BackendApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClerkClientPublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkClientSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CreateApiKeyStreamProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GrowthStrategyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OnboardingStreamProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OpenAIApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OrderManagerQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OrderTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "ProcessDeliverableStreamProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "StripePriceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TechStrategyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UnkeyApiId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UnkeyRootKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ValueStrategyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WebsiteReviewQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}