/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "Agents": {
      "tableName": string
      "type": "aws.dynamodb/table.Table"
    }
    "ApiKeyStreamProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ApiKeys": {
      "tableName": string
      "type": "aws.dynamodb/table.Table"
    }
    "BackendApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "ClerkClientPublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkClientSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ClerkWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CreateApiKeyStreamProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Deliverables": {
      "tableName": string
      "type": "aws.dynamodb/table.Table"
    }
    "GrowthStrategyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "OnboardingStreamProcessor": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OpenAIApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Orders": {
      "tableName": string
      "type": "aws.dynamodb/table.Table"
    }
    "PriceID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhookSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TasksTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "TechStrategyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "UnkeyApiId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UnkeyRootKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Users": {
      "tableName": string
      "type": "aws.dynamodb/table.Table"
    }
    "ValueStrategyQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "WebsiteReview": {
      "tableName": string
      "type": "aws.dynamodb/table.Table"
    }
    "WebsiteReviewQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}
